server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_service
    username: springstudent
    password: springstudent
  jpa:
    properties:
      javax:
        persistence:
          validation:
            mode: none
    hibernate:
      ddl-auto: update
    open-in-view: false
  main:
    #    web-application-type: none
    banner-mode: off
  application:
    name: auth-service
app:
  routesMicroservices:
    tokenService:
      generateToken: http://localhost:8079/tokenservice/generatetoken
    userService:
      registerUser: http://localhost:8082/userservice/registeruser
  routesController:
    requestmapping:
      unlocked:
        authServiceController: /auth
    notlocked:
      login:
        authUser: /login
        registerUser: /register
  jwtSecret: S5arZ8qX8Anvk60LIHdGKZiGyLAyxW+LU1Xw2H4R6Uu1ndlUNPqhpVuKtFsfFvA+
  jwtCryptoSecret : sBnlg0BGosgPMQju